### ISSUE TITLE
Pesquisar informações da Câmara no Google

### ISSUE THREAD

**Issue by marciovilasboas** [cmjatai/SaplMobile#1]
Possibilitar a pesquisa através do botão pesquisar(lupa) das informações da Casa que estiver utilizando e não apenas a de Jatai.

**Comment by LeandroJatai** [comment]
Olá Marcio,
desculpe a demora...  Sapl Web 3.1 tá tomando o tempo geral mas consegui fazer hoje a alteração de sua sugestão. Acabei de publicar na Play Store, versão 1.018, deve estar disponível em breve.

**Comment by marciovilasboas** [comment]
Oi Leandro, acho que todos que utilizam o SAPL Mobile vão ficar
agradecidos pela alteração sugerida.
Já atualizei para a versão 1.018 e está ok agora.
Parabéns pelo trabalho colaborativo.

abs,

Em 12-04-2016 11:04, Leandro Roberto da Silva escreveu:

> Olá Marcio,
> desculpe a demora Sapl Web 3.1 tá tomando o tempo geral mas consegui
> fazer hoje a alteração de sua sugestão. Acabei de publicar na Play
> Store, versão 1.018, deve estar disponível em breve.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cmjatai/SaplMobile/issues/1#issuecomment-208922950

## 

/Márcio Vilas Boas/
/Consultoria de Informática/
/CM - Divinópolis - MG/
/(37) 2102-8236/

**Comment by paulot12** [comment]
Adaptar para aparecer as informações do 3.1?

**Comment by LeandroJatai** [comment]
Olá @paulot12, está nos planos compatibilizar o SaplMobile com o Sapl 3.1.
